
export interface PersonalInfo {
  fullName: string;
  email: string;
  phone: string;
  linkedin?: string;
  location: string;
}

export interface Experience {
  role: string;
  company: string;
  period: string;
  description: string[];
}

export interface Education {
  degree: string;
  institution: string;
  period: string;
}

export interface Skill {
  category: string;
  items: string[];
}

export interface Project {
  name: string;
  description: string;
  technologies: string[];
  link?: string;
}

export interface Certification {
    name: string;
    issuer: string;
    date: string;
}

export interface Language {
    language: string;
    proficiency: 'Native' | 'Fluent' | 'Conversational' | 'Basic';
}

// Represents the data of an uploaded PDF file
export interface PdfDataPart {
    fileName: string;
    mimeType: 'application/pdf';
    data: string; // base64 encoded string
}

// The tailored, concise resume profile generated by the AI
export interface TailoredResume {
  personalInfo: PersonalInfo;
  summary: string;
  experience: Experience[];
  education: Education[];
  skills: Skill[];
}

// The comprehensive knowledge base uploaded by the user
export interface UserKnowledgeBase {
  personalInfo: PersonalInfo;
  professionalSummaryBase: string; // A generic summary to be adapted
  experience: Experience[];
  education: Education[];
  skills: Skill[];
  projects: Project[];
  certifications: Certification[];
  languages: Language[];
}
